// Writes THIRD_PARTY_NOTICES.md: the licences of everything uncoil's binaries carry that uncoil didn't write.
//
//   node scripts/notices/notices.mjs           (needs cargo-about: cargo install cargo-about --locked --features cli)
//   node scripts/notices/notices.mjs --check   (exit 1 if the committed file is out of date)
//
// - Rust: every crate compiled into uncoild, uncoil.exe and the app (cargo-about, about.toml; build and dev
//   dependencies are left out, they don't ship).
// - The app's front end: exactly the npm packages whose code is in the bundle, read from the source maps of a
//   one-off build (then rebuilt without maps), plus Tailwind, whose base styles are in the CSS.
// - Code adapted into uncoil itself: FastLED's rainbow hue map (crates/uncoil-core/src/color.rs).
import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../..');
const app = join(root, 'apps/uncoil');
const out = join(root, 'THIRD_PARTY_NOTICES.md');
const win = process.platform === 'win32';
const run = (cmd, args, cwd) => execFileSync(cmd, args, { cwd, encoding: 'utf8', maxBuffer: 64 << 20, shell: win, stdio: ['ignore', 'pipe', 'inherit'] });
const lf = (s) => s.replace(/\r\n/g, '\n').trim();

// ---- Rust ----------------------------------------------------------------------------------------------
// to a file: cargo-about refuses to write to a pipe from PowerShell
const rustFile = join(tmpdir(), `uncoil-notices-${process.pid}.md`);
run('cargo', ['about', 'generate', '--locked', '-c', join(here, 'about.toml'), '-o', rustFile, join(here, 'about.hbs')], root);
const rust = lf(readFileSync(rustFile, 'utf8'));
rmSync(rustFile);

// ---- npm: the packages in the bundle -------------------------------------------------------------------
run('pnpm', ['exec', 'vite', 'build', '--sourcemap'], app);
const bundled = new Set(['tailwindcss']);
const walk = (dir) => readdirSync(dir, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)]));
for (const map of walk(join(app, '.svelte-kit/output/client')).filter((f) => f.endsWith('.map'))) {
	for (const src of JSON.parse(readFileSync(map, 'utf8')).sources ?? []) {
		const m = /node_modules[\\/](?:\.pnpm[\\/][^\\/]+[\\/]node_modules[\\/])?((?:@[^\\/]+[\\/])?[^\\/]+)/.exec(src);
		if (m) bundled.add(m[1].replace(/\\/g, '/'));
	}
}
// the real build, without source maps
run('pnpm', ['exec', 'vite', 'build'], app);

/** npm packages that ship no licence file, and the Rust crate (same repository, same licence) that does. */
const SAME_AS_CRATE = { '@tauri-apps/plugin-opener': 'tauri-plugin-opener' };
const listed = Object.values(JSON.parse(run('pnpm', ['licenses', 'list', '--json'], app))).flat();
const npm = [];
for (const name of [...bundled].sort()) {
	const p = listed.find((x) => x.name === name);
	if (!p) throw new Error(`${name} is in the bundle but pnpm doesn't list it`);
	const dir = p.paths[0];
	// LICENSE, LICENSE.md, or one file per licence of a dual-licensed package (LICENSE-MIT, LICENSE-APACHE-2.0)
	const files = readdirSync(dir).filter((f) => /^(licen[cs]e|copying)([-.](?!spdx$)[\w.-]+)?$/i.test(f)).sort();
	if (!files.length) {
		// a package without a licence file: its Rust crate from the same repository carries the text above
		const crate = SAME_AS_CRATE[name];
		if (!crate || !rust.includes(`${crate} `)) throw new Error(`${name} ${p.versions[0]} has no licence file in ${dir}`);
		npm.push(`### ${name} ${p.versions[0]} (${p.license})\n\nThe package has no licence file of its own. It is the front end of the Rust crate \`${crate}\`, from the same repository and under the same licence, whose text is listed under Rust crates above.`);
		continue;
	}
	const texts = files.map((f) => `\`\`\`text\n${lf(readFileSync(join(dir, f), 'utf8'))}\n\`\`\``);
	npm.push(`### ${name} ${p.versions[0]} (${p.license})\n\n${texts.join('\n\n')}`);
}

// ---- together ------------------------------------------------------------------------------------------
const text = `# Third-party notices

uncoil is free software under the GNU General Public License, version 3 or later (see LICENSE). Its
binaries (\`uncoild.exe\`, \`uncoil.exe\` and the desktop app) also contain the work of others, under the
licences below. Generated by \`node scripts/notices/notices.mjs\`; don't edit by hand.

Crates under the Mozilla Public License 2.0 are used unmodified; their source is on https://crates.io.

## Code adapted into uncoil

### FastLED (MIT): the rainbow hue map in \`crates/uncoil-core/src/color.rs\`

\`\`\`text
${lf(readFileSync(join(here, 'FastLED-LICENSE.txt'), 'utf8'))}
\`\`\`

## Rust crates

${rust}

## The desktop app's front end (npm)

${npm.join('\n\n')}
`;

if (process.argv.includes('--check')) {
	const now = existsSync(out) ? readFileSync(out, 'utf8').replace(/\r\n/g, '\n') : '';
	if (now !== text) {
		console.error('THIRD_PARTY_NOTICES.md is out of date; run node scripts/notices/notices.mjs');
		process.exit(1);
	}
	console.log('THIRD_PARTY_NOTICES.md is up to date');
} else {
	writeFileSync(out, text);
	console.log(`wrote ${out}: ${rust.split('\n### ').length} Rust licence texts, ${npm.length} npm packages`);
}
